default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: kudos_tracker_development

test: &test
  <<: *default
  database: kudos_tracker_test

production:
  <<: *default
